language: perl
perl:
  - "5.18"
  - "5.14"
  - "5.10"
env:
  - "HARNESS_OPTIONS=j1"
install:
  - "cpanm -n Test::Pod Test::Pod::Coverage Mojolicious"
  - "cpanm -n --installdeps ."
notifications:
  email: false
